[조화] 행복한 가정은
onealand/quotations-book pull request #6
Opened 2024-12-24 13:43 UTC by shangcom

## 아래 내용을 읽고 완료가 되었다면 [x]를 표시해주세요.

- [x] 해당 PR의 제목 형식은 `[테마] 문장`으로 해주세요. (문장이 길면 짧게 요약)
  - `ex) [마음] 너에게 묻는다`
- [x] 커밋 메시지는 양식에 맞게 잘 작성했나요?
- [x] 작성한 문장이 테마 디렉터리와 적합한가요?
- [x] 번역한 문장은 적절한가요?
- [x] Main의 README.md에 테마에 맞게 잘 넣었나요?

2024-12-30 06:04 UTC, YeonjiKim0316 approved these changes

2024-12-30 06:05 UTC, YeonjiKim0316 approved these changes

2024-12-30 09:11 UTC, onealog requested changes
코멘트 내용 참고하여 수정 부탁 드립니다 ! 🙂

2024-12-30 09:11 UTC, onealog commented on README.md
> +- [행복한 가정은 모두 비슷한 이유로 행복하지만 불행한 가정은 저마다의 이유로 불행하다.](./theme/harmony/anna-karenina)
```suggestion
- [행복한 가정은 모두 비슷한 이유로 행복하지만 불행한 가정은 저마다의 이유로 불행하다](./theme/harmony/anna-karenina)
```

끝에 점(`.`)을 붙이지 않습니다.

2024-12-30 09:11 UTC, onealog commented on theme/harmony/anna-karanina.md
이름만 다르고 내용이 동일한 파일이 2개 만들어져 있네요.   
해당 파일을 삭제하는 게 맞을 듯 합니다! (`anna-karanina.md` 파일)

2024-12-30 09:11 UTC, onealog commented on theme/harmony/anna-karenina.md
> +안나 카레니라(레프 톨스토이)
```suggestion
안나 카레니나(레프 톨스토이)
```
오타로 보입니다.

2024-12-31 07:20 UTC, onealog commented
@shangcom 님 안녕하세요!   
수정사항 모두 확인했고, 잘 수정해주셨네요!   
다만, 커밋 메시지가 양식에 맞지 않습니다.   
도서에 `rebase` 부분 참고하셔서 커밋 메시지 양식 변경하시고 다시 올려주세요 ! 🙏

2024-12-31 08:06 UTC, shangcom commented
선생님, 친절하게 가르쳐주셔서 감사합니다. 
git push --force-with-lease origin harmony/anna-karenina
위의 명령어를 사용하였는데 옳은 방법인지 잘 모르겠습니다.
연말연시 잘 보내시기 바랍니다.

2025-01-01 13:28 UTC, onealog commented
> 선생님, 친절하게 가르쳐주셔서 감사합니다. git push --force-with-lease origin harmony/anna-karenina 위의 명령어를 사용하였는데 옳은 방법인지 잘 모르겠습니다. 연말연시 잘 보내시기 바랍니다.

@shangcom 님, 저도 해당 명령어는 처음 접하는데요 :)   
책에 보면 `git rebase -i ~`에 대한 내용이 있을 거예요.   
로컬에서 `git rebase -i ~` 명령어를 활용해서 최근 3개의 커밋의 메시지만 양식대로 변경해주신 다음,   
깃허브로 올릴 때 `git push -f ~`로 강제 푸시 해보세요! (`git push --force ~` 와 동일한 명령어)
강제 푸시 하는 이유는 최근 3개의 커밋이 삭제되고 새로운 커밋으로 바뀌었기 때문에 그냥 푸시를 할 경우 푸시가 안되기 때문입니다.   
   
그리고 양식은 [여기](https://github.com/onealand/quotations-book#4-%EB%AA%85%EC%96%B8-%EC%9E%91%EC%84%B1%ED%95%98%EA%B8%B0) 참고하셔서 `[대문자]: 커밋 메시지`로  작성해주시고,   
여기 프로젝트에서는 `[REMOVE]` 대신 `[DELETE]`를 사용하고 있고 `[DOCS]`는 따로 양식에 없으니 `[CHORE]`로 해주시면 되겠습니다!   
   
새해 복 많이 받으세요!

2025-01-02 03:19 UTC, shangcom commented
@onealog 이번엔 통과가 가능할지요. 제 자신이 꼼꼼한 사람이라고 생각했는데, 혼자 공부하다 보니 어느새 얼렁뚱땅이 습관이 되었나봅니다. 반성합니다. 선생님 덕분에 크게 배웠습니다. 앞서도 말씀드렸지만, 친절하게 가르쳐 주셔서 감사합니다. 새해 복 많이 받으세요!

2025-01-02 09:23 UTC, onealog approved these changes, later dismissed
고생하셨습니다! 👍👍👍   
[Merge pull request] 버튼을 직접 눌러서 머지하시면 프로젝트에 적용됩니다!

2025-01-03 09:15 UTC, onealog commented on README.md
> +- [행복한 가정은 모두 비슷한 이유로 행복하지만 불행한 가정은 저마다의 이유로 불행하다](./theme/harmony/anna-karenina)
```suggestion
- [행복한 가정은 모두 비슷한 이유로 행복하지만 불행한 가정은 저마다의 이유로 불행하다](./theme/harmony/anna-karenina.md)
```
아 제가 하나 빼먹었네요! 여기 뒤에 `.md`도 붙여주셔야 합니다!

2025-01-04 05:13 UTC, shangcom commented on README.md
> +- [행복한 가정은 모두 비슷한 이유로 행복하지만 불행한 가정은 저마다의 이유로 불행하다](./theme/harmony/anna-karenina)
틀린 부분이 너무 많아서 숨고 싶네요. 꼼꼼히 검토해주셔서 감사드립니다!

2025-01-05 13:45 UTC, onealog commented
@shangcom 고생하셨습니다. 실무에 들어가면 틀리고, 빼 먹는 일은 비일비재합니다 ㅎㅎ   
이런 걸로 기죽지 마세요. 틀리거나 빠뜨린 건 고치면 되니까요!   
그러니까, 이런 `Pull Request` 과정이 있는 거예요~

2025-01-06 02:32 UTC, shangcom commented
@onealog 혼자 공부하는데다 팀으로 뭔가를 해본 적이 없어서 처음 해보는 풀 리퀘스트라 긴장했는데, 피드백을 보니 잘못된 부분이 많아서 당황했습니다. 가이드라인이 있고 시간도 얼마든지 있었는데도 불구하구요. 마지막에 주신 말씀을 보며 깃도 깃이지만 전반적인 태도를 점검해야겠다는 생각을 했습니다. 많은걸 배웠습니다. 감사합니다.

2025-01-06 04:18 UTC, onealog commented
> @onealog 혼자 공부하는데다 팀으로 뭔가를 해본 적이 없어서 처음 해보는 풀 리퀘스트라 긴장했는데, 피드백을 보니 잘못된 부분이 많아서 당황했습니다. 가이드라인이 있고 시간도 얼마든지 있었는데도 불구하구요. 마지막에 주신 말씀을 보며 깃도 깃이지만 전반적인 태도를 점검해야겠다는 생각을 했습니다. 많은걸 배웠습니다. 감사합니다.

@shangcom 저 정도는 많은 게 아닙니다. 🙂   
저도 실무에서는 많은 실수를 해요. 사소한 실수는 누구나 하니까요..!   
첨부 이미지처럼 버튼이 보이시다면 눌러서 머지해보세요! 안보이시면 말씀해주세요~   
![image](https://github.com/user-attachments/assets/8071ebc1-b129-4c98-b1ad-b36592e5d387)

2025-01-06 04:58 UTC, shangcom commented
@onealog 버튼이 없습니다. 아래와 같이 나옵니다.
![capture](https://github.com/user-attachments/assets/8b3bcabb-6ca0-4a71-bb53-3a6982c4c9a9)

2025-01-07 12:19 UTC, onealog approved these changes
@shangcom 설정을 바꿔보았는데요! 지금도 여전히 안보이나요~?

2025-01-07 12:28 UTC, shangcom commented
@onealog 네, 지금도 보이지 않습니다.

2025-01-08 04:18 UTC, onealog commented
@shangcom 아 그럼 일단은 제가 머지하겠습니다! 고생하셨습니다! 👍

2025-01-08 04:18 UTC, merged

2025-01-08 05:45 UTC, shangcom commented
감사합니다. 고생하셨습니다.

2025년 1월 8일 (수) 오후 1:18, ONE:A (Jaewon Han) ***@***.***>님이 작성:

> Merged #6 <https://github.com/onealand/quotations-book/pull/6> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/onealand/quotations-book/pull/6#event-15847291442>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDXLRWIMDDNMA4TVTACVNMT2JSRJTAVCNFSM6AAAAABUEXWBCKVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJVHA2DOMRZGE2DIMQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>